apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-kafka-producer-helm-chart.name" . }}-config-map
  namespace: {{ include "quarkus-kafka-producer-helm-chart.name" . }}-namespace
data:
  KAFKA_BOOTSTRAP_SERVERS: crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092
  KAFKA_CONNECTOR: smallrye-kafka
  KAFKA_OUTPUT_TOPIC: amedeosarpa.kafka-topic
  KAFKA_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer