apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-kafka-producer-helm-chart.name" . }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "quarkus-kafka-producer-helm-chart.name" . }}-deployment
    namespace: {{ .Values.global.namespace }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}