# Default values for quarkus-kafka-producer-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080

ingress:
  annotations:
     ingress:
       class: nginx

deployment:
  containers:
    image: producer-image
    name: quarkus-kafka-producer-name