apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-kafka-consumer-helm-chart.name" . }}-config-map
  namespace: {{ include "quarkus-kafka-consumer-helm-chart.name" . }}-namespace
data:
  KAFKA_BOOTSTRAP_SERVERS: crs-kafka-0.kafka-cluster.default.svc.cluster.local:9092
  KAFKA_CONNECTOR: smallrye-kafka
  KAFKA_INPUT_TOPIC: amedeosarpa.kafka-topic
  KAFKA_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer