apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-kafka-consumer-helm-chart.name" . }}-config-map
  namespace: {{ .Values.global.namespace }}
data:
  KAFKA_INPUT_TOPIC: amedeosarpa.kafka-topic
  KAFKA_KEY_DESERIALIZER: com.amedeosarpa.dto.MeasurementRecordDeserializer