name: devops-rumpup-poc's pipeline by amedeosarpa

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'devops-fils'

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      quarkus-kafka-producer: ${{ steps.filter.outputs.quarkus-kafka-producer }}
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          quarkus-kafka-producer:
            - 'quarkus-kafka-producer/**'


  quarkus-kafka-producer:

    needs: detect-changes

    # run only if some file in 'quarkus-kafka-producer' folder was changed
    if: ${{ needs.detect-changes.outputs.quarkus-kafka-producer == 'true' }}
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -f quarkus-kafka-producer/pom.xml

    - name: Build and Push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: amedeosarpa/quarkus-kafka-producer
        registry: docker.io
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: quarkus-kafka-producer/Dockerfile

